title: Your awesome title
tagline: The Jekyll Butler
paginate: 1
baseurl: ""
permalink: pretty
url: https://dealingwith.github.io/jamespeilunli/

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: James
  url: ""
  email: ""
